ARG PORT
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY
ARG AWS_REGION
ARG AWS_CLOUDWATCH_GROUP_NAME

FROM node:18

ENV PORT $PORT
ENV AWS_ACCESS_KEY $AWS_ACCESS_KEY
ENV AWS_SECRET_KEY $AWS_SECRET_KEY
ENV AWS_REGION $AWS_REGION
ENV AWS_CLOUDWATCH_GROUP_NAME $AWS_CLOUDWATCH_GROUP_NAME

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

EXPOSE $PORT
ENTRYPOINT ["npm", "start"]