version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: prj
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_CLOUDWATCH_GROUP_NAME=${AWS_CLOUDWATCH_GROUP_NAME}
    ports:
      - ${PORT}:${PORT}
